services:
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Exception,Model,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # fixtures are imported separately to make sure services can be injected
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    # prefix all table with "app" to prevent name collision
    App\Doctrine\AppPrefix:
        tags:
            - { name: doctrine.event_subscriber }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    JMS\Serializer\SerializerInterface:
        alias: jms_serializer

    App\Service\MediaService:
        arguments:
            $mediaFolder: '%env(MEDIA_FOLDER)%'

